user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

topic:
    resource: "@TopicBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
